'use client';
// import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Script from "next/script";

const inter = Inter({ subsets: ["latin"] });

declare const window: {
  vaticaiTracker?: any; // Optional type allows undefined value initially
};

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Script
        src="https://pixel.vaticai.com/static/js/pixel.js"
        strategy="lazyOnload"
        onLoad={() => {
          console.log(`script loaded correctly, window.FB has been populated`)
          window.vaticaiTracker = window.vaticaiTracker || [];
          console.log("window",window.vaticaiTracker)
          window.vaticaiTracker.siteIdentifier ="NEXT_APP"

        }
      }
      />
      <body className={inter.className}>{children}</body>
    </html>
  );
}
